server:
  port: 8080

spring:
  application:
    name: cafemanagement
  datasource:
    url: jdbc:mysql://localhost:3306/nineVol
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update